import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const aller = localFont({
  src: [
    {
      path: "../public/fonts/Aller_It.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Aller_Rg.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-aller",
});

const tanAegean = localFont({
  src: [
    {
      path: "../public/fonts/TAN-AEGEAN-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-tan-aegean",
});

export const metadata: Metadata = {
  title: "Beryan Co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${aller.variable} ${tanAegean.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">{children}</body>
    </html>
  );
}
